### ISSUE TITLE
Description field is broken

### ISSUE THREAD

**Issue by ridvanaltun** [KvanTTT/NppGist#19]
**Notepad++:** v8.1.4
**NppGist:** v1.5.0.31

The description area covers the entire right section as seen in the image below and I cannot access some buttons for this reason.

![image](https://user-images.githubusercontent.com/10441216/132956855-efb87d8d-3b68-4824-9c70-ae6753d5e65b.png)

**Comment by KvanTTT** [comment]
Could you describe the sequence of actions to reproduce this issue? Do resize anchors work?

**Comment by ridvanaltun** [comment]
> Quite strange. Could you describe the sequence of actions to reproduce this issue? Do resize anchors work?

Resizing anchors did not fix the issue. The issue occurs when I open the NppGist window, nothing special.

**Comment by ridvanaltun** [comment]
I opened the project with Visual Studio and check the design from the source code, the same issue also exists when in Visual Studio. Buttons are located out of the form view. I can easily solve the issue by drag buttons to the form view. I can open a PR for this but what do you think?

Also, I have a question, how can I update a Gist content with NppGist? There is no button for update Gist in the toolbar or anywhere. I share a picture below to show how my toolbar looks like.

![Screenshot 2021-09-12 001658](https://user-images.githubusercontent.com/10441216/132962007-9f9b9472-379e-42fe-ac7b-5b3f87806bfc.png)

**Comment by KvanTTT** [comment]
> I opened the project with Visual Studio and check the design from the source code, the same issue also exists when in Visual Studio. Buttons are located out of the form view. I can easily solve the issue by drag buttons to the form view. I can open a PR for this but what do you think?

It's strange because they are located fine for me. I'll try to view it on a monitor with another resolution. But PR is also welcome.

> Also, I have a question, how can I update a Gist content with NppGist? There is no button for update Gist in the toolbar or anywhere.

Sure you can. I merged both forms into a single one in [1.5.0](https://github.com/KvanTTT/NppGist/releases/tag/1.5.0). Save button is available there.

![image](https://user-images.githubusercontent.com/1150330/132985042-d912963d-bf69-447a-a17c-c8cbaa2195f7.png)

> I share a picture below to show how my toolbar looks like.

Hmm, it looks like there is also something wrong with the icon. I don't have artifacts with displaying:

![image](https://user-images.githubusercontent.com/1150330/132984976-033087b7-e71c-4c8d-9ae8-6f12acbf19a6.png)

**Comment by vico93** [comment]
I have a similar issue as OP. Using NPP 8.6, NppGist 1.5.1.35 and Windows 11.

**Comment by vico93** [comment]
Any updates about this? Still having the issue. My screen resolution is 1366x768.

**Comment by KvanTTT** [comment]
No. If you want, you can try to figure out the problem by yourself and suggest a PR.
